### ISSUE TITLE
mongo-connector is not working with elasticsearch 2

### ISSUE THREAD

**Issue by rahman13dec4u** [yougov/mongo-connector#813] opened 2018-04-23 03:48 UTC
elastic2-doc-manager and mongo-connector has been installed....
--------------------------------------------------------------
```
[root@strl099151 ~]# pip freeze | grep -Ei "elastic|mongo"
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
elastic2-doc-manager==0.3.0
elasticsearch==2.4.1
mongo-connector==2.5.1
pymongo==3.6.1
[root@strl099151 ~]#
```
----------------------------------------

 Error : 
-------------------------------------------------------- 

```
[root@strl099151 ~]# /usr/bin/mongo-connector -m strl099151:27017 -t strl099151:9200 -d elastic2_doc_manager

Traceback (most recent call last):
  File "/usr/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 1275, in main
    conf.parse_args()
  File "/usr/lib/python2.7/site-packages/mongo_connector/config.py", line 120, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 1012, in apply_doc_managers
    DocManager = import_dm_by_name(dm['docManager'])
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 981, in import_dm_by_name
    return import_dm_by_path(full_name)
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 1001, in import_dm_by_path
    "vailable doc managers. ImportError:\n%s" % (package, exc))
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers. ImportError:
Error: elasticsearch (https://pypi.python.org/pypi/elasticsearch) version 2.x or 5.x is not installed.
Install with:
  pip install elastic-doc-manager[elastic2]
or:
  pip install elastic-doc-manager[elastic5]
```
------------------------------------------------------------------------

```
[root@strl099151 ~]# curl 172.21.99.151:9200
{
  "name" : "Crystal",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.3",
    "build_hash" : "<hash>",
    "build_timestamp" : "2016-05-17T15:40:04Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
[root@strl099151 ~]# curl 172.21.99.151:27017
It looks like you are trying to access MongoDB over HTTP on the native driver port.
[root@strl099151 ~]#
```

Please help me why i'm getting this error.

**Comment by DreamerCather** [comment] 2018-10-26 13:35
I have the same problem as you ,I suspect if my elasticsearch is not the right location

**Comment by malekascha** [comment] 2018-10-30 19:21
I've run into the same issue. Here's the traceback:
Traceback (most recent call last):

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 29, in <module>

19:12:05
import elasticsearch

19:12:05
ImportError: No module named 'elasticsearch'

19:12:05
During handling of the above exception, another exception occurred:

19:12:05
Traceback (most recent call last):

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/connector.py", line 1084, in import_dm_by_path

19:12:05
module = __import__(package, fromlist=(package,))

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 32, in <module>

19:12:05
"Error: elasticsearch (https://pypi.python.org/pypi/elasticsearch) "

19:12:05
ImportError: Error: elasticsearch (https://pypi.python.org/pypi/elasticsearch) version 2.x or 5.x is not installed.

19:12:05
Install with:

19:12:05
pip install elastic-doc-manager[elastic2]

19:12:05
or:

19:12:05
pip install elastic-doc-manager[elastic5]

19:12:05
During handling of the above exception, another exception occurred:

19:12:05
Traceback (most recent call last):

19:12:05
File "/usr/local/bin/mongo-connector", line 11, in <module>

19:12:05
sys.exit(main())

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/util.py", line 107, in wrapped

19:12:05
func(*args, **kwargs)

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/connector.py", line 1395, in main

19:12:05
conf.parse_args()

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/config.py", line 125, in parse_args

19:12:05
option, dict((k, values.get(k)) for k in option.cli_names)

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/connector.py", line 1108, in apply_doc_managers

19:12:05
DocManager = import_dm_by_name(dm["docManager"])

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/connector.py", line 1075, in import_dm_by_name

19:12:05
return import_dm_by_path(full_name)

19:12:05
File "/usr/local/lib/python3.4/site-packages/mongo_connector/connector.py", line 1095, in import_dm_by_path

19:12:05
"vailable doc managers. ImportError:\n%s" % (package, exc)

19:12:05
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers. ImportError:

19:12:05
Error: elasticsearch (https://pypi.python.org/pypi/elasticsearch) version 2.x or 5.x is not installed.

19:12:05
Install with:

19:12:05
pip install elastic-doc-manager[elastic2]

19:12:05
or:

19:12:05
pip install elastic-doc-manager[elastic5]

Similar to @DreamerCather, it looks like the doc manager fails to find elasticsearch, leading the mongo-connector to say that the doc manager I want to use is not available. I've tried reinstalling everything fresh more than once, and it hasn't fixed it.

A little more info about the environment I'm running it in: it's in a docker container, with the following dockerfile:

`#This will prepare a elasticsearch node with mongo-connector enabled

FROM python:3.4.3

ARG version
RUN pip install certifi
RUN pip install elastic2-doc-manager[aws]
COPY install_mongo_connector.sh .
RUN chmod u+x ./install_mongo_connector.sh && bash ./install_mongo_connector.sh $version

ENV DEBIAN_FRONTEND noninteractive

# Installing Mongo Connector which will connect MongoDB and Elasticsearch

COPY startup.sh /tmp/
COPY set_access_keys.py .
COPY config_template_ES2.json .
COPY empty_oplog .

COPY mongo /usr/bin/
RUN chmod a+x /usr/bin/mongo

VOLUME /data


# Sample usage when no commands is given outside
CMD ["/bin/bash", "/tmp/startup.sh"]`

This is the startup script:

`#!/bin/bash

mongo="${MONGO:-mongo}"
mongoport="${MONGOPORT:-27017}"
elasticsearch="${ELASTICSEARCH}"

python set_access_keys.py

function _mongo() {
    mongo --quiet --host ${mongo} --port ${mongoport} <<EOF
    $@
EOF
}

is_master_result="false"
expected_result="true"

while true;
do
  if [ "${is_master_result}" == "${expected_result}" ] ; then
    is_master_result=$(_mongo "rs.isMaster().ismaster")
    echo "Waiting for Mongod node to assume primary status..."
    sleep 3
  else
    echo "Mongod node is now primary"
    break;
  fi
done

sleep 1

mongo-connector -c ./config.json -m ${mongo}:${mongoport} -t ${elasticsearch} -o "./empty_oplog"
`

Config Template: 

`{
  "docManagers": [
    {
      "docManager": "elastic2_doc_manager",
      "targetURL": "ELASTICSEARCH URL",
      "args": {
        "aws": {
            "region": "us-west-2",
            "access_id": "ACCESS KEY",
            "secret_key": "SECRET KEY"
        },
        "clientOptions": {
          "verify_certs": true,
          "use_ssl": true,
          "timeout": 60
        }
      }
    }
  ],
  "logging": {
    "type": "stream"
  },
  "verbosity": 1,
}`

Any help or troubleshooting advice you can offer would be greatly appreciated!

**Comment by rahman13dec4u** [comment] 2018-10-30 22:40
HI Malek,
I got that error because my IT team upgraded python-urllib3 on my server to  python-urllib3-1.10.2-2.el7_1.noarch.After downgrading to "python-urllib3-1.10.2-5.el7.noarch" fixed my issue.

**Comment by malekascha** [comment] 2018-11-01 21:16
Manually installing elasticsearch with pip solved the issue it seems. Not sure where it went wrong.

**Comment by jaraco** [comment] 2018-11-06 19:05
I can confirm that the error message is incorrect. It should not be referencing elastic-doc-manager, but instead elastic2-doc-manager.

But the main error, that elasticsearch seems to be installed, is probably an issue with a confused install environment. You're probably running `pip` and `mongo-connector` from different environments.

What you need to do is `head $(which /usr/bin/mongo-connector/)` - which should point to which Python executable/environment is associated with that command. Then with that Python executable, do `.../python -m pip freeze | grep elastic`, which will probably reveal that you don't have elasticsearch installed in that Python environment.

If there's an issue with installation, I'm not able to replicate it. I'm going to close this issue, but if you're able to replicate the issue in a clean environment (something like Docker), I'd be happy to help troubleshoot.

**Closed by jaraco** 2018-11-06 19:05 UTC
